server:
  port: 80
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes: # https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-route-definition
        - id: instruments-route
          uri: http://localhost:8181
          predicates:
            - Path=/instruments/**
            - Host={segment}.localhost # for demo purpose we use subdomain to route to the right tenant, but for production I should use a header since I don't know how to create a DNS entry for each tenant
          filters:
            - AddRequestHeader=X-TenantId, {segment}

#          - id: prometheus
#            uri: http://prometheus:9090
#            predicates:
#              - Path=/prometheus/**
#            filters:
#              - RewritePath=/prometheus/(?<segment>.*), /$\{segment}
#          - id: tempo
#            uri: http://tempo:3100
#            predicates:
#              - Path=/tempo/**
#            filters:
#              - RewritePath=/tempo/(?<segment>.*), /$\{segment}
#          - id: loki
#            uri: http://loki:3100
#            predicates:
#              - Path=/loki/**
#            filters:
#              - RewritePath=/loki/(?<segment>.*), /$\{segment}
#          - id: grafana
#            uri: http://grafana:3000
#            predicates:
#              - Path=/grafana/**
#            filters:
#              - RewritePath=/grafana/(?<segment>.*), /$\{segment}
#          - id: jaeger
#            uri: http://jaeger:16686
#            predicates:
#              - Path=/jaeger/**
#            filters:
#              - RewritePath=/jaeger/(?<segment>.*), /$\{segment}
#          - id: zipkin
#            uri: http://zipkin:9411
#            predicates:
#              - Path=/zipkin/**
#            filters:
#              - RewritePath=/zipkin/(?<segment>.*), /$\{segment}

#        - id: actuator
#          uri: http://localhost:8080
#          predicates:
#            - Path=/actuator/**
#          filters:
#            - RewritePath=/actuator/(?<segment>.*), /$\{segment}
#        - id: swagger
#          uri: http://localhost:8080
#          predicates:
#            - Path=/swagger/**
#          filters:
#            - RewritePath=/swagger/(?<segment>.*), /$\{segment}
#        - id: swagger-ui
#          uri: http://localhost:8080
#          predicates:
#            - Path=/swagger-ui/**
#          filters:
#            - RewritePath=/swagger-ui/(?<segment>.*), /$\{segment}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] tenantId=%X{tenantId:-}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always

tenant:
  security:
    client-id: edge-service
    client-secret: rocking-secret
    issuer-base-uri: http://localhost:8080